version = 0.1
[default.deploy.parameters]
stack_name = "ofertas-3dgames"
resolve_s3 = true
s3_prefix = "ofertas-3dgames"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["Ofertas3dgamesFunction=869579352973.dkr.ecr.us-east-1.amazonaws.com/ofertas3dgamescd567635/ofertas3dgamesfunction637362efrepo"]
