AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ofertas 3dgames

Globals:
  Function:
    Timeout: 10

Resources:
  MeliFullSalesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: 'applications-db'
        - SQSSendMessagePolicy:
            QueueName: !ImportValue TelegramMessageQueueName
      Environment:
        Variables:
          SQS_QUEUE_URL: !ImportValue TelegramMessageQueueUrl
          ENVIRONMENT: prod
      Events:
        MeliFullSalesSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(5 minute)'
            Name: Ofertas3dgamesSchedule
            Description: Ofertas 3dgames schedule
            Enabled: true
