AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ofertas 3dgames

Globals:
  Function:
    Timeout: 60
    MemorySize: 256

Resources:
  Ofertas3dgamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: 'applications-db'
        - SQSSendMessagePolicy:
            QueueName: !ImportValue TelegramMessageQueueName
      Environment:
        Variables:
          SQS_QUEUE_URL: !ImportValue TelegramMessageQueueUrl
          ENVIRONMENT: prod
      Events:
        Ofertas3dgamesSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(5 minutes)'
            Name: Ofertas3dgamesSchedule
            Description: Ofertas 3dgames schedule
            Enabled: true
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile